---
- name: Setup cert-manager
  # Run this playbook only on the first control plane node
  hosts: controlplane[0]
  become: yes
  gather_facts: false

  tasks:
    - name: Add cert-manager Helm repository
      ansible.builtin.command:
        cmd: helm repo add jetstack https://charts.jetstack.io
      changed_when: false
      failed_when: false # Ignore errors if the repo already exists

    - name: Update Helm repositories
      ansible.builtin.command:
        cmd: helm repo update
      changed_when: false

    - name: Install or upgrade cert-manager Helm chart
      ansible.builtin.command:
        # Explicitly point to the kubeconfig file for authentication
        cmd: >
          helm upgrade --install cert-manager jetstack/cert-manager
          --namespace cert-manager
          --create-namespace
          --set installCRDs=true
          --kubeconfig /etc/kubernetes/admin.conf
      changed_when: true

    - name: Wait for cert-manager deployments to be ready
      ansible.builtin.command:
        cmd: kubectl wait --for=condition=Available deployment --all -n cert-manager --timeout=5m --kubeconfig /etc/kubernetes/admin.conf
      changed_when: false