- name: Install and Configure Cilium
  hosts: controlplane[0]
  become: yes
  gather_facts: false
  vars:
    cluster_config: "{{ lookup('file', '../../tmp/{{ cluster_name }}/cluster_config.json') | from_json }}"
    replica_count: "{{ 2 if (groups['controlplane'] | length) > 1 else 1 }}"
    cilium_config_path: "/tmp/cilium_config.yaml"
    hubble_netpol_path: "/tmp/hubble-ui-netpol.yaml"
    hubble_ingress_path: "/tmp/cilium-hubble-ingress.yaml"

  tasks:
    - name: Generate Cilium Config from template
      ansible.builtin.template:
        src: ../../helpers/cilium_config.yaml.j2
        dest: "{{ cilium_config_path }}"
        mode: '0644'

    - name: Add Cilium Helm repository
      ansible.builtin.command:
        cmd: helm repo add cilium https://helm.cilium.io/
      changed_when: false
      failed_when: false # Ignore if repo already exists

    - name: Update Helm repositories
      ansible.builtin.command:
        cmd: helm repo update
      changed_when: false

    - name: Install Cilium Helm chart
      ansible.builtin.command:
        cmd: >
          helm upgrade --install cilium cilium/cilium
          --version {{ cilium_version }}
          --namespace kube-system
          --create-namespace
          --values {{ cilium_config_path }}
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      changed_when: true

    - name: Generate Hubble UI NetworkPolicy from template
      ansible.builtin.template:
        src: ../../helpers/hubble-ui-netpol.yaml.j2
        dest: "{{ hubble_netpol_path }}"
        mode: '0644'
      when: cluster_config.networking.cilium.hubble.ui.enabled | default(false)

    - name: Apply Hubble UI NetworkPolicy
      ansible.builtin.command:
        cmd: "kubectl apply -f {{ hubble_netpol_path }}"
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      changed_when: true
      when: cluster_config.networking.cilium.hubble.ui.enabled | default(false)

    - name: Generate Hubble UI Ingress from template
      ansible.builtin.template:
        src: ../../helpers/cilium-hubble-ingress.yaml.j2
        dest: "{{ hubble_ingress_path }}"
        mode: '0644'
      when: cluster_config.networking.cilium.hubble.ui.enabled | default(false) and cluster_config.networking.cilium.hubble.ui.ingress.enabled | default(false)

    - name: Apply Hubble UI Ingress
      ansible.builtin.command:
        cmd: "kubectl apply -f {{ hubble_ingress_path }}"
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      changed_when: true
      when: cluster_config.networking.cilium.hubble.ui.enabled | default(false) and cluster_config.networking.cilium.hubble.ui.ingress.enabled | default(false)
