---
- name: Setup NGINX Ingress Controller
  hosts: controlplane[0]
  become: yes
  gather_facts: false

  tasks:
    - name: Add NGINX Ingress Controller Helm repository
      ansible.builtin.command:
        cmd: helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
      changed_when: false
      failed_when: false

    - name: Update Helm repositories
      ansible.builtin.command:
        cmd: helm repo update
      changed_when: false

    - name: Install NGINX Ingress Controller Helm chart
      ansible.builtin.command:
        # --wait ensures Helm doesn't exit until the deployment is fully available.
        # This is the most critical part for webhook readiness.
        cmd: >
          helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx
          --namespace ingress-nginx
          --create-namespace
          --wait
          --timeout 10m
          --kubeconfig /etc/kubernetes/admin.conf
      changed_when: true
      
    - name: Ensure NGINX Ingress Controller is ready before proceeding
      ansible.builtin.command:
        cmd: kubectl wait --for=condition=Available deployment/ingress-nginx-controller -n ingress-nginx --timeout=5m --kubeconfig /etc/kubernetes/admin.conf
      changed_when: false