- name: Create RuntimeClass for alternative runtimes
  hosts: controlplane[0]
  gather_facts: false
  vars:
    cluster_config: "{{ lookup('file', '../../tmp/{{ cluster_name }}/cluster_config.json') | from_json }}"
  tasks:
    - name: Create RuntimeClass for gVisor
      when: cluster_config.runtime == 'gvisor'
      become: true
      kubernetes.core.k8s:
        state: present
        kubeconfig: /etc/kubernetes/admin.conf
        definition:
          apiVersion: node.k8s.io/v1
          kind: RuntimeClass
          metadata:
            name: gvisor
          handler: gvisor

    - name: Create RuntimeClass for Kata
      when: cluster_config.runtime == 'kata'
      become: true
      kubernetes.core.k8s:
        state: present
        kubeconfig: /etc/kubernetes/admin.conf
        definition:
          apiVersion: node.k8s.io/v1
          kind: RuntimeClass
          metadata:
            name: kata
          handler: kata
